/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled 2"
  https://create.arduino.cc/cloud/things/374a43a9-3af7-49fe-b36d-0fac478c3b3f 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  int num;
  bool led;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

unsigned long previousMillis = 0;  
const long interval = 1500;
int data = 0;

void setup() {
  num = 0;
  led = false;
  Serial.begin(115200);
  delay(1500); 
  initProperties();
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  setDebugMessageLevel(0);
  ArduinoCloud.printDebugInfo();
  pinMode(num, OUTPUT);

}

void loop() {
  ArduinoCloud.update();
  
  unsigned long currentMillis = millis();
  if (Serial.available())
  {
    if (currentMillis - previousMillis >= interval)
    {
      previousMillis = currentMillis;
      num = getData();
    }
  }
}



void onNumChange()  {
  
}


void onLedChange()  {

}

int getData()
{
  if (Serial.available())
  {
    String s = Serial.readStringUntil('\n'); // for incoming serial data
    s.trim();
    data = s.toInt();
  }
  
  else
  {
    data = 0;
  }
  
  return data;
}
